<?php

    return [
        "categorias_nome" => [
            0 => "Equipamento Articulares",
            1 => "Equipamento de Musculação",
            2 => "Equipamento de Cross",
            3 => "Equipamento de Ar Livre",
            4 => "Equipamento de Box",
            5 => "Equipamentos de Bike Indoor/Outdoor",
            6 => "Equipamento de Anilhas",
            7 => "Equipamento de Atletismo",
            8 => "Equipamento de Natação",
            9 => "Equipamento de Fisioterapia",
            10 => "Equipamento de Filmagem",
            11 => "Equipamentos de Som",
            12 => "Djs para Evento",
            13 => "Programas de Danças",
            14 => "Programas Funcionais ",
            15 => "Franquias",
            16 => "Livros ",
            17 => "Acessórios para Avaliação Física",
            18 => "Acessório para Dança Clássica",
            19 => "Acessório para Bike ",
            20 => "Acessório para Fisioterapia",
            21 => "Acessório Fitness",
            22 => "Esportes Radicais ",
            23 => "Suplementação",
            24 => "Produtos Naturais",
            25 => "Marmita Fitness",
            26 => "Moda Fitness",
            27 => "Uniforme Esportivo",
            28 => "Marcas Esportivas",
            29 => "Lojas Esportivas ",
            30 => "Estética Fitness",
            31 => "Agência de Marketing ",
            32 => "Consultoria Fitness",
            33 => "Comunicação Visual",
            34 => "Sistema Inteligente",
            35 => "Sistema de Gegestão ",
            36 => "Instituição Financeira ",
            37 => "Acessória Gympass",
            38 => "Corretora de Seguros",
            39 => "Arquitetos",
            40 => "Consultoria Jurídica",
            41 => "Tecnólogia ",
            42 => "Entidades e Sinticados ",
            43 => "Orgãos eFederações",
            44 => "Convênios",
            45 => "Adquirintes",
            46 => "Tecnólogia ",
            47 => "Ibstituição Financeira ",
            48 => "Benefícios Colaboradores",
            49 => "Programa Fidelidade",
            50 => "Aplicativos",
            51 => "Rádio e TV Online",
            52 => "Monitoramento",
            53 => "Moveis e Decoração",
            54 => "Bebedouros",
            55 => "Limpeza",
            56 => "Peças de Manutenção",
            57 => "Iluminação",
            58 => "Refrigeração",
            59 => "Brindes e Acessórios ",
            60 => "Papelaria",
            61 => "Brinquedoteca",
            62 => "Pisos e Grama",
            63 => "Influencers Fitness",
            64 => "Catrácas para Academia ",
            65 => "Body Arte para Fisiculturismo ",
            66 => "Músicas para Treino e Academia ",

        ]
    ];

?>